### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lifangzhen** [ran-jit/TomcatClusterRedisSessionManager#2]

**Comment by ran-jit** [comment]
Hi @lifangzhen,

Null handling and some additional features added in the latest version. Kindly upgrade your version to latest and check the same.

Thank you !

**Comment by ran-jit** [comment]
Hi @lifangzhen,

I've identified few tomcat-7 compatibility issues and fixed in the latest version.

The fix is available in 2.0.1 release. (https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/2.0.1). I request you to kindly upgrade your session manager from version x to 2.0.1.

#### Migration procedure from 1.x to 2.x
 * Replace redis data-cache properties in tomcat/conf directory.
 * Update the below lines in tomcat/conf/context.xml file.
        `<Valve className="tomcat.request.session.redis.SessionHandlerValve" />`
        `<Manager className="tomcat.request.session.redis.SessionManager" />`

Please revert if any issues.

Thanks!
